# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sitemate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire', '~> 4.4'
    pod 'RealmSwift', '~> 3.18.0'
    pod "ObjectMapper+Realm"

  target 'SitemateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SitemateUITests' do
    # Pods for testing
  end

end
